force-app/main/default/objects/Inventory_Items__c/Inventory_Items__c.object-meta.xml
<CustomObject>
    <description>Cópias de um filme</description>
    <label>Inventory Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Switch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InventoryItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/InventoryItemBOTest.cls
@isTest
public with sharing class InventoryItemBOTest {

    @isTest
    public static void testWatcherAvailability() {
      List<Inventory_Items__c> testInventories = new List<Inventory_Items__c>();
      Inventory_Items__c testItem = new Inventory_Items__c();
      testItem.Status__c = 'Available';
      testInventories.add(testItem);

      Test.startTest();
      InventoryItemBO.watcherAvailability(testInventories);
      Test.stopTest();
    }

    @isTest
    public static void testHandleDisponibilityItem() {
      Inventory_Items__c testItem = new Inventory_Items__c();
      testItem.Status__c = 'Available';

      Test.startTest();
      Reservation__c result = InventoryItemBO.handleDisponibilityItem(testItem);
      Test.stopTest();
    }
}