force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/Inventory_Items__c.object-meta.xml
<CustomObject>
    <description>Cópias de um filme</description>
    <label>Inventory Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Switch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InventoryItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <description>Relação com inventory</description>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>InventoryItems</relationshipLabel>
    <relationshipName>InventoryItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Items__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/helpers/inventoryItem/InventoryItemBO.cls
public with sharing class InventoryItemBO {

  public static void watcherAvailability(List<Inventory_Items__c> inventories) {
    List<Reservation__c> updateReservations = new List<Reservation__c>();

    for(Inventory_Items__c item: inventories) {
      Reservation__c reservation = handleDisponibilityItem(item);
      if (reservation != null) {
        updateReservations.add(reservation);
      }
    }

    update updateReservations;
  }

  public static Reservation__c handleDisponibilityItem(Inventory_Items__c item) {
    Reservation__c reservationToUpdate;

    if(item.Status__c == 'Available') {

      List<Reservation__c> reservations = ReservationDAO.getByInventoryId(item.Inventory__c);

      if(reservations.size() > 0) {
        reservationToUpdate = reservations.get(0);

        reservationToUpdate.Inventory_Items__c = item.Id;
        reservationToUpdate.Status__c = 'await rent';
        reservationToUpdate.Initial_Reserva__c = System.today();

        Contact contact = ContactDAO.getByIds(new Set<Id>{reservationToUpdate.Contact__c})[0];

        Inventory__c inventory = InventoryDAO.getByIds(new Set<Id>{reservationToUpdate.Inventory__c})[0];

        Email email =  new Email();
        email.updateReservation(contact.Name, contact.Email, inventory.Name);

        item.Status__c = 'Reserved';
      }
    }

    return reservationToUpdate;
  }
}