force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/Inventory_Items__c.object-meta.xml
<CustomObject>
    <description>Cópias de um filme</description>
    <label>Inventory Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Switch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InventoryItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <description>Relação com inventory</description>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>InventoryItems</relationshipLabel>
    <relationshipName>InventoryItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Items__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rent__c/Rent__c.object-meta.xml
<CustomObject>
    <label>Rent</label>
    <nameField>
        <displayFormat>RENT-{0000}</displayFormat>
        <label>Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Relação com contato</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rents</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rent__c/fields/Inventory_Items__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Items__c</fullName>
    <description>Relação com cópias do filme</description>
    <label>Inventory Items</label>
    <referenceTo>Inventory_Items__c</referenceTo>
    <relationshipLabel>Rents</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/RentBOTest.cls
@isTest
public with sharing class RentBOTest {
  @isTest
    static void testValidateCloseDate() {
        Rent__c rent = new Rent__c(Close_Date__c = System.today());
        insert rent;

        Test.startTest();
        RentBO.validateCloseDate(new List<Rent__c>{ rent });
        Test.stopTest();

        
        System.assert(rent.hasErrors(), 'A data de entrega não pode ser menor ou igual a data de hoje, por obséquio escolha outra data!');
    }

    @isTest
    static void testValidateStatusItem() {

        Inventory__c inventory = new Inventory__c(Name='Teste');
        insert inventory;
      
        
        Inventory_Items__c item = new Inventory_Items__c(Inventory__c = inventory.Id, Status__c = 'Available');
        insert item;

        Rent__c rent = new Rent__c(Inventory_Items__c = item.Id);
        insert rent;

      
        Reservation__c reservation = new Reservation__c();
        insert reservation;

        Test.startTest();
        RentBO.validateStatusItem(new List<Rent__c>{ rent });
        Test.stopTest();

 
        System.assert(rent.hasErrors(), 'Erro esperado não foi adicionado');
    }




    @isTest
    static void testHandleReservation() {
        Inventory__c inventory = new Inventory__c(Name='teste inventory');
        Contact contact = new Contact(FirstName='teste');
        Inventory_Items__c item = new Inventory_Items__c(Inventory__c = inventory.Id);
        
        Rent__c rent = new Rent__c(Contact__c = contact.Id, Inventory_Items__c = item.Id);
        insert rent;

       
        Reservation__c reservation = RentBO.handleReservation(rent);

       
        System.assertNotEquals(null, reservation);
        System.assertEquals('completed', reservation.Status__c);
        System.assertNotEquals('completed', reservation.Status__c);
    }
}