force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/Inventory_Items__c.object-meta.xml
<CustomObject>
    <description>Cópias de um filme</description>
    <label>Inventory Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Switch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InventoryItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Items__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <description>Relação com inventory</description>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>InventoryItems</relationshipLabel>
    <relationshipName>InventoryItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Items__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/selectors/reservation/ReservationDAO.cls
public with sharing class ReservationDAO {
  public static List<Reservation__c> getByInventoryId(Id inventoryId) {
    return [
      SELECT
        Id,
        Contact__c,
        Inventory__c,
        Inventory_Items__c,
        Status__c,
        Initial_Reserva__c
      FROM Reservation__c
      WHERE Inventory__c = :inventoryId
      AND Status__c = 'await item'
    ];
  }

  public static List<Reservation__c> getByContactAndItem(Id contactId, Id itemId) {
    return [
      SELECT
        Id,
        Contact__c,
        Inventory_Items__c,
        Status__c
      FROM Reservation__c
      WHERE Contact__c = :contactId
      AND Inventory_Items__c = :itemId
      AND Status__c = 'await rent'
    ];
  }

}